#!/usr/bin/env python3

file = open('CO-OPS.csv')
next(file)
max_water = 0
max_date = 0
for line in file:
   column = line.split(",")
   water_level = column[1]
   datetime = column[0]
   if water_level > max_water:
      max_water = water_level
      max_date = datetime
print "The maximum water level was", max_water, "and occurred on", max_date

